name: Publish to NPM

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: sudo apt update -y 
        
      - run: sudo npm install

      - name: Publish to NPM
        run: sudo npm start
